/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const EffectScope: typeof import('vue').EffectScope
  const TAB_LIST: typeof import('./stores/index').TAB_LIST
  const acceptHMRUpdate: typeof import('pinia').acceptHMRUpdate
  const appStore: typeof import('./stores/index').appStore
  const applyThemeDom: typeof import('./stores/theme').applyThemeDom
  const bootTheme: typeof import('./stores/theme').bootTheme
  const bubbleRef: typeof import('./utils/login-bubble').bubbleRef
  const computed: typeof import('vue').computed
  const createApp: typeof import('vue').createApp
  const createPinia: typeof import('pinia').createPinia
  const customRef: typeof import('vue').customRef
  const defineAsyncComponent: typeof import('vue').defineAsyncComponent
  const defineComponent: typeof import('vue').defineComponent
  const defineStore: typeof import('pinia').defineStore
  const effectScope: typeof import('vue').effectScope
  const getActivePinia: typeof import('pinia').getActivePinia
  const getCurrentInstance: typeof import('vue').getCurrentInstance
  const getCurrentScope: typeof import('vue').getCurrentScope
  const getCurrentWatcher: typeof import('vue').getCurrentWatcher
  const h: typeof import('vue').h
  const hideNativeTabBarIfNeeded: typeof import('./utils/navigation').hideNativeTabBarIfNeeded
  const initTheme: typeof import('./stores/theme').initTheme
  const inject: typeof import('vue').inject
  const isDark: typeof import('./stores/theme').isDark
  const isProxy: typeof import('vue').isProxy
  const isReactive: typeof import('vue').isReactive
  const isReadonly: typeof import('vue').isReadonly
  const isRef: typeof import('vue').isRef
  const isShallow: typeof import('vue').isShallow
  const lockDocumentTitle: typeof import('./utils/favicon').lockDocumentTitle
  const mapActions: typeof import('pinia').mapActions
  const mapGetters: typeof import('pinia').mapGetters
  const mapState: typeof import('pinia').mapState
  const mapStores: typeof import('pinia').mapStores
  const mapWritableState: typeof import('pinia').mapWritableState
  const markRaw: typeof import('vue').markRaw
  const migrateLegacyTokens: typeof import('./utils/storage').migrateLegacyTokens
  const nextTick: typeof import('vue').nextTick
  const onActivated: typeof import('vue').onActivated
  const onAddToFavorites: typeof import('@dcloudio/uni-app').onAddToFavorites
  const onBackPress: typeof import('@dcloudio/uni-app').onBackPress
  const onBeforeMount: typeof import('vue').onBeforeMount
  const onBeforeUnmount: typeof import('vue').onBeforeUnmount
  const onBeforeUpdate: typeof import('vue').onBeforeUpdate
  const onDeactivated: typeof import('vue').onDeactivated
  const onError: typeof import('@dcloudio/uni-app').onError
  const onErrorCaptured: typeof import('vue').onErrorCaptured
  const onHide: typeof import('@dcloudio/uni-app').onHide
  const onLaunch: typeof import('@dcloudio/uni-app').onLaunch
  const onLoad: typeof import('@dcloudio/uni-app').onLoad
  const onMounted: typeof import('vue').onMounted
  const onNavigationBarButtonTap: typeof import('@dcloudio/uni-app').onNavigationBarButtonTap
  const onNavigationBarSearchInputChanged: typeof import('@dcloudio/uni-app').onNavigationBarSearchInputChanged
  const onNavigationBarSearchInputClicked: typeof import('@dcloudio/uni-app').onNavigationBarSearchInputClicked
  const onNavigationBarSearchInputConfirmed: typeof import('@dcloudio/uni-app').onNavigationBarSearchInputConfirmed
  const onNavigationBarSearchInputFocusChanged: typeof import('@dcloudio/uni-app').onNavigationBarSearchInputFocusChanged
  const onPageNotFound: typeof import('@dcloudio/uni-app').onPageNotFound
  const onPageScroll: typeof import('@dcloudio/uni-app').onPageScroll
  const onPullDownRefresh: typeof import('@dcloudio/uni-app').onPullDownRefresh
  const onReachBottom: typeof import('@dcloudio/uni-app').onReachBottom
  const onReady: typeof import('@dcloudio/uni-app').onReady
  const onRenderTracked: typeof import('vue').onRenderTracked
  const onRenderTriggered: typeof import('vue').onRenderTriggered
  const onResize: typeof import('@dcloudio/uni-app').onResize
  const onScopeDispose: typeof import('vue').onScopeDispose
  const onServerPrefetch: typeof import('vue').onServerPrefetch
  const onShareAppMessage: typeof import('@dcloudio/uni-app').onShareAppMessage
  const onShareTimeline: typeof import('@dcloudio/uni-app').onShareTimeline
  const onShow: typeof import('@dcloudio/uni-app').onShow
  const onTabItemTap: typeof import('@dcloudio/uni-app').onTabItemTap
  const onThemeChange: typeof import('@dcloudio/uni-app').onThemeChange
  const onUnhandledRejection: typeof import('@dcloudio/uni-app').onUnhandledRejection
  const onUnload: typeof import('@dcloudio/uni-app').onUnload
  const onUnmounted: typeof import('vue').onUnmounted
  const onUpdated: typeof import('vue').onUpdated
  const onWatcherCleanup: typeof import('vue').onWatcherCleanup
  const provide: typeof import('vue').provide
  const reactive: typeof import('vue').reactive
  const readonly: typeof import('vue').readonly
  const ref: typeof import('vue').ref
  const resolveComponent: typeof import('vue').resolveComponent
  const resolvedTheme: typeof import('./stores/theme').resolvedTheme
  const setActivePinia: typeof import('pinia').setActivePinia
  const setMapStoreSuffix: typeof import('pinia').setMapStoreSuffix
  const setSquareFavicon: typeof import('./utils/favicon').setSquareFavicon
  const setTheme: typeof import('./stores/theme').setTheme
  const setupRouteAuthGuard: typeof import('./utils/route-auth').setupRouteAuthGuard
  const shallowReactive: typeof import('vue').shallowReactive
  const shallowReadonly: typeof import('vue').shallowReadonly
  const shallowRef: typeof import('vue').shallowRef
  const startBubble: typeof import('./utils/login-bubble').startBubble
  const stopBubble: typeof import('./utils/login-bubble').stopBubble
  const storage: typeof import('./utils/storage').storage
  const storeToRefs: typeof import('pinia').storeToRefs
  const syncDocumentTitle: typeof import('./utils/favicon').syncDocumentTitle
  const themeMode: typeof import('./stores/theme').themeMode
  const toRaw: typeof import('vue').toRaw
  const toRef: typeof import('vue').toRef
  const toRefs: typeof import('vue').toRefs
  const toValue: typeof import('vue').toValue
  const toggleTheme: typeof import('./stores/theme').toggleTheme
  const triggerRef: typeof import('vue').triggerRef
  const unref: typeof import('vue').unref
  const useAppStore: typeof import('./stores/index').useAppStore
  const useAttrs: typeof import('vue').useAttrs
  const useCssModule: typeof import('vue').useCssModule
  const useCssVars: typeof import('vue').useCssVars
  const useH5MobileTabShell: typeof import('./utils/h5-tab-layout').useH5MobileTabShell
  const useId: typeof import('vue').useId
  const useModel: typeof import('vue').useModel
  const useSlots: typeof import('vue').useSlots
  const useStore: typeof import('./stores/index').useStore
  const useTemplateRef: typeof import('vue').useTemplateRef
  const useThemeStore: typeof import('./stores/theme').useThemeStore
  const useUserStore: typeof import('./stores/user').useUserStore
  const userStore: typeof import('./stores/user').userStore
  const watch: typeof import('vue').watch
  const watchEffect: typeof import('vue').watchEffect
  const watchPostEffect: typeof import('vue').watchPostEffect
  const watchSyncEffect: typeof import('vue').watchSyncEffect
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, ShallowRef, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { TabName } from './stores/app'
  import('./stores/app')
  // @ts-ignore
  export type { ThemeMode } from './stores/theme'
  import('./stores/theme')
  // @ts-ignore
  export type { AppUser, UserTokenPayload } from './stores/user'
  import('./stores/user')
}

// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface GlobalComponents {}
  interface ComponentCustomProperties {
    readonly EffectScope: UnwrapRef<typeof import('vue')['EffectScope']>
    readonly TAB_LIST: UnwrapRef<typeof import('./stores/index')['TAB_LIST']>
    readonly acceptHMRUpdate: UnwrapRef<typeof import('pinia')['acceptHMRUpdate']>
    readonly appStore: UnwrapRef<typeof import('./stores/index')['appStore']>
    readonly applyThemeDom: UnwrapRef<typeof import('./stores/theme')['applyThemeDom']>
    readonly bootTheme: UnwrapRef<typeof import('./stores/theme')['bootTheme']>
    readonly bubbleRef: UnwrapRef<typeof import('./utils/login-bubble')['bubbleRef']>
    readonly computed: UnwrapRef<typeof import('vue')['computed']>
    readonly createApp: UnwrapRef<typeof import('vue')['createApp']>
    readonly createPinia: UnwrapRef<typeof import('pinia')['createPinia']>
    readonly customRef: UnwrapRef<typeof import('vue')['customRef']>
    readonly defineAsyncComponent: UnwrapRef<typeof import('vue')['defineAsyncComponent']>
    readonly defineComponent: UnwrapRef<typeof import('vue')['defineComponent']>
    readonly defineStore: UnwrapRef<typeof import('pinia')['defineStore']>
    readonly effectScope: UnwrapRef<typeof import('vue')['effectScope']>
    readonly getActivePinia: UnwrapRef<typeof import('pinia')['getActivePinia']>
    readonly getCurrentInstance: UnwrapRef<typeof import('vue')['getCurrentInstance']>
    readonly getCurrentScope: UnwrapRef<typeof import('vue')['getCurrentScope']>
    readonly getCurrentWatcher: UnwrapRef<typeof import('vue')['getCurrentWatcher']>
    readonly h: UnwrapRef<typeof import('vue')['h']>
    readonly hideNativeTabBarIfNeeded: UnwrapRef<typeof import('./utils/navigation')['hideNativeTabBarIfNeeded']>
    readonly initTheme: UnwrapRef<typeof import('./stores/theme')['initTheme']>
    readonly inject: UnwrapRef<typeof import('vue')['inject']>
    readonly isDark: UnwrapRef<typeof import('./stores/theme')['isDark']>
    readonly isProxy: UnwrapRef<typeof import('vue')['isProxy']>
    readonly isReactive: UnwrapRef<typeof import('vue')['isReactive']>
    readonly isReadonly: UnwrapRef<typeof import('vue')['isReadonly']>
    readonly isRef: UnwrapRef<typeof import('vue')['isRef']>
    readonly isShallow: UnwrapRef<typeof import('vue')['isShallow']>
    readonly lockDocumentTitle: UnwrapRef<typeof import('./utils/favicon')['lockDocumentTitle']>
    readonly mapActions: UnwrapRef<typeof import('pinia')['mapActions']>
    readonly mapGetters: UnwrapRef<typeof import('pinia')['mapGetters']>
    readonly mapState: UnwrapRef<typeof import('pinia')['mapState']>
    readonly mapStores: UnwrapRef<typeof import('pinia')['mapStores']>
    readonly mapWritableState: UnwrapRef<typeof import('pinia')['mapWritableState']>
    readonly markRaw: UnwrapRef<typeof import('vue')['markRaw']>
    readonly migrateLegacyTokens: UnwrapRef<typeof import('./utils/storage')['migrateLegacyTokens']>
    readonly nextTick: UnwrapRef<typeof import('vue')['nextTick']>
    readonly onActivated: UnwrapRef<typeof import('vue')['onActivated']>
    readonly onAddToFavorites: UnwrapRef<typeof import('@dcloudio/uni-app')['onAddToFavorites']>
    readonly onBackPress: UnwrapRef<typeof import('@dcloudio/uni-app')['onBackPress']>
    readonly onBeforeMount: UnwrapRef<typeof import('vue')['onBeforeMount']>
    readonly onBeforeUnmount: UnwrapRef<typeof import('vue')['onBeforeUnmount']>
    readonly onBeforeUpdate: UnwrapRef<typeof import('vue')['onBeforeUpdate']>
    readonly onDeactivated: UnwrapRef<typeof import('vue')['onDeactivated']>
    readonly onError: UnwrapRef<typeof import('@dcloudio/uni-app')['onError']>
    readonly onErrorCaptured: UnwrapRef<typeof import('vue')['onErrorCaptured']>
    readonly onHide: UnwrapRef<typeof import('@dcloudio/uni-app')['onHide']>
    readonly onLaunch: UnwrapRef<typeof import('@dcloudio/uni-app')['onLaunch']>
    readonly onLoad: UnwrapRef<typeof import('@dcloudio/uni-app')['onLoad']>
    readonly onMounted: UnwrapRef<typeof import('vue')['onMounted']>
    readonly onNavigationBarButtonTap: UnwrapRef<typeof import('@dcloudio/uni-app')['onNavigationBarButtonTap']>
    readonly onNavigationBarSearchInputChanged: UnwrapRef<typeof import('@dcloudio/uni-app')['onNavigationBarSearchInputChanged']>
    readonly onNavigationBarSearchInputClicked: UnwrapRef<typeof import('@dcloudio/uni-app')['onNavigationBarSearchInputClicked']>
    readonly onNavigationBarSearchInputConfirmed: UnwrapRef<typeof import('@dcloudio/uni-app')['onNavigationBarSearchInputConfirmed']>
    readonly onNavigationBarSearchInputFocusChanged: UnwrapRef<typeof import('@dcloudio/uni-app')['onNavigationBarSearchInputFocusChanged']>
    readonly onPageNotFound: UnwrapRef<typeof import('@dcloudio/uni-app')['onPageNotFound']>
    readonly onPageScroll: UnwrapRef<typeof import('@dcloudio/uni-app')['onPageScroll']>
    readonly onPullDownRefresh: UnwrapRef<typeof import('@dcloudio/uni-app')['onPullDownRefresh']>
    readonly onReachBottom: UnwrapRef<typeof import('@dcloudio/uni-app')['onReachBottom']>
    readonly onReady: UnwrapRef<typeof import('@dcloudio/uni-app')['onReady']>
    readonly onRenderTracked: UnwrapRef<typeof import('vue')['onRenderTracked']>
    readonly onRenderTriggered: UnwrapRef<typeof import('vue')['onRenderTriggered']>
    readonly onResize: UnwrapRef<typeof import('@dcloudio/uni-app')['onResize']>
    readonly onScopeDispose: UnwrapRef<typeof import('vue')['onScopeDispose']>
    readonly onServerPrefetch: UnwrapRef<typeof import('vue')['onServerPrefetch']>
    readonly onShareAppMessage: UnwrapRef<typeof import('@dcloudio/uni-app')['onShareAppMessage']>
    readonly onShareTimeline: UnwrapRef<typeof import('@dcloudio/uni-app')['onShareTimeline']>
    readonly onShow: UnwrapRef<typeof import('@dcloudio/uni-app')['onShow']>
    readonly onTabItemTap: UnwrapRef<typeof import('@dcloudio/uni-app')['onTabItemTap']>
    readonly onThemeChange: UnwrapRef<typeof import('@dcloudio/uni-app')['onThemeChange']>
    readonly onUnhandledRejection: UnwrapRef<typeof import('@dcloudio/uni-app')['onUnhandledRejection']>
    readonly onUnload: UnwrapRef<typeof import('@dcloudio/uni-app')['onUnload']>
    readonly onUnmounted: UnwrapRef<typeof import('vue')['onUnmounted']>
    readonly onUpdated: UnwrapRef<typeof import('vue')['onUpdated']>
    readonly onWatcherCleanup: UnwrapRef<typeof import('vue')['onWatcherCleanup']>
    readonly provide: UnwrapRef<typeof import('vue')['provide']>
    readonly reactive: UnwrapRef<typeof import('vue')['reactive']>
    readonly readonly: UnwrapRef<typeof import('vue')['readonly']>
    readonly ref: UnwrapRef<typeof import('vue')['ref']>
    readonly resolveComponent: UnwrapRef<typeof import('vue')['resolveComponent']>
    readonly resolvedTheme: UnwrapRef<typeof import('./stores/theme')['resolvedTheme']>
    readonly setActivePinia: UnwrapRef<typeof import('pinia')['setActivePinia']>
    readonly setMapStoreSuffix: UnwrapRef<typeof import('pinia')['setMapStoreSuffix']>
    readonly setSquareFavicon: UnwrapRef<typeof import('./utils/favicon')['setSquareFavicon']>
    readonly setTheme: UnwrapRef<typeof import('./stores/theme')['setTheme']>
    readonly setupRouteAuthGuard: UnwrapRef<typeof import('./utils/route-auth')['setupRouteAuthGuard']>
    readonly shallowReactive: UnwrapRef<typeof import('vue')['shallowReactive']>
    readonly shallowReadonly: UnwrapRef<typeof import('vue')['shallowReadonly']>
    readonly shallowRef: UnwrapRef<typeof import('vue')['shallowRef']>
    readonly startBubble: UnwrapRef<typeof import('./utils/login-bubble')['startBubble']>
    readonly stopBubble: UnwrapRef<typeof import('./utils/login-bubble')['stopBubble']>
    readonly storage: UnwrapRef<typeof import('./utils/storage')['storage']>
    readonly storeToRefs: UnwrapRef<typeof import('pinia')['storeToRefs']>
    readonly syncDocumentTitle: UnwrapRef<typeof import('./utils/favicon')['syncDocumentTitle']>
    readonly themeMode: UnwrapRef<typeof import('./stores/theme')['themeMode']>
    readonly toRaw: UnwrapRef<typeof import('vue')['toRaw']>
    readonly toRef: UnwrapRef<typeof import('vue')['toRef']>
    readonly toRefs: UnwrapRef<typeof import('vue')['toRefs']>
    readonly toValue: UnwrapRef<typeof import('vue')['toValue']>
    readonly toggleTheme: UnwrapRef<typeof import('./stores/theme')['toggleTheme']>
    readonly triggerRef: UnwrapRef<typeof import('vue')['triggerRef']>
    readonly unref: UnwrapRef<typeof import('vue')['unref']>
    readonly useAppStore: UnwrapRef<typeof import('./stores/index')['useAppStore']>
    readonly useAttrs: UnwrapRef<typeof import('vue')['useAttrs']>
    readonly useCssModule: UnwrapRef<typeof import('vue')['useCssModule']>
    readonly useCssVars: UnwrapRef<typeof import('vue')['useCssVars']>
    readonly useH5MobileTabShell: UnwrapRef<typeof import('./utils/h5-tab-layout')['useH5MobileTabShell']>
    readonly useId: UnwrapRef<typeof import('vue')['useId']>
    readonly useModel: UnwrapRef<typeof import('vue')['useModel']>
    readonly useSlots: UnwrapRef<typeof import('vue')['useSlots']>
    readonly useStore: UnwrapRef<typeof import('./stores/index')['useStore']>
    readonly useTemplateRef: UnwrapRef<typeof import('vue')['useTemplateRef']>
    readonly useThemeStore: UnwrapRef<typeof import('./stores/theme')['useThemeStore']>
    readonly useUserStore: UnwrapRef<typeof import('./stores/user')['useUserStore']>
    readonly userStore: UnwrapRef<typeof import('./stores/user')['userStore']>
    readonly watch: UnwrapRef<typeof import('vue')['watch']>
    readonly watchEffect: UnwrapRef<typeof import('vue')['watchEffect']>
    readonly watchPostEffect: UnwrapRef<typeof import('vue')['watchPostEffect']>
    readonly watchSyncEffect: UnwrapRef<typeof import('vue')['watchSyncEffect']>
  }
}